import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jake1.net",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <script defer data-domain="jake1.net" src="https://analytics.jake1.net/js/script.js"></script>
      </head>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen bg-zinc-50 dark:bg-gradient-to-br from-indigo-800 from-10% via-sky-600 via-40% to-indigo-700 to-90% dark:text-white">
          <Header />
          <main className="flex-1 pt-20 pr-1 md:pr-0">
            <div className="container mx-auto p-4">{children}</div>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}